version: "3.8"
services:
  app:
    build: 
      context: ./.docker/nginx
    container_name: gao-webserver
    tty: true
    volumes:
      - .:/var/www/
      - .docker/logs/nginx:/var/log/nginx
    depends_on:
      - php

    

    labels: 
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:gao.localhost"

  php:
    build:
      args:
        user: gao-laravel-vuejs
        uid: 1000
      context: ./.docker/php
    container_name: gao-php
    ports:
      - 9000:9000
    links:
      - db:mysqldb 
    volumes:
      - .:/var/www/
    
  db:
    image: mysql:5.7
    container_name: gao-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9306:3306
    volumes:
      - .docker/volumes/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gao
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  traefik: 
    image: traefik:1.7
    container_name: gao-traefik
    command: --docker --docker.exposedbydefault=false
    ports: 
      - "80:80"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro